[
    {
        "duration": 6840,
        "elevationGained": 0,
        "elevationLost": 0,
        "endTime": 1463527783000,
        "fare": null,
        "legs": [
            {
                "agencyId": null,
                "agencyName": null,
                "agencyTimeZoneOffset": 3600000,
                "agencyUrl": null,
                "alerts": null,
                "alightRule": null,
                "arrivalDelay": 0,
                "boardRule": null,
                "departureDelay": 0,
                "distance": 4242.94807439751,
                "duration": 3256,
                "endTime": 1463524199000,
                "from": {
                    "arrival": null,
                    "departure": 1463520943000,
                    "lat": 41.1083549,
                    "lon": -8.5064236,
                    "name": "road",
                    "orig": "",
                    "platformCode": null,
                    "stopCode": null,
                    "stopId": null,
                    "stopIndex": null,
                    "zoneId": null
                },
                "headsign": null,
                "headway": null,
                "interlineWithPreviousLeg": false,
                "intermediateStops": null,
                "isNonExactFrequency": null,
                "legGeometry": {
                    "length": 138,
                    "levels": null,
                    "points": "e~{yFdl|r@MR[JaANw@PKPIh@?T@v@AjADf@Jx@\\dALd@Fr@?v@Ev@IhA_I`Ba@AWAoEyA}@AiEtAm@N]@sBBUr@_@bBCh@GlBIXWb@iAhBoAhFcAn@Gp@KxAQ`@iCtGKb@Od@UX}@j@C@mAx@Q\\Eh@@RE?CBCDAF?FYFcA?m@Bo@JeAPo@Pg@Xc@Za@@_@EiAYq@Mu@Ke@A_@@GDa@b@aAn@s@h@WTSp@a@hBUp@OPUB_@F]DYP_@^e@r@_@Z]Ja@Aa@?c@Bc@VyBvAwA|@qAr@}@Zq@VODoATiB^sAXsBv@iAjAKJU\\a@Vi@b@i@bA[NcEnBqAr@qAx@YRm@t@Yp@EFaAnAc@ZgDtBiEhAoA\\oAr@m@`Ao@r@KVQn@M\\?F?DADABA@C@C?SFOPGNCTJzC@\\"
                },
                "mode": "WALK",
                "notes": null,
                "realTime": false,
                "rentedBike": false,
                "route": "",
                "routeColor": null,
                "routeId": null,
                "routeLongName": null,
                "routeShortName": null,
                "routeTextColor": null,
                "routeType": null,
                "serviceDate": null,
                "startTime": 1463520943000,
                "steps": [
                    {
                        "absoluteDirection": "NORTHWEST",
                        "alerts": null,
                        "area": false,
                        "bogusName": false,
                        "distance": 377.74269744973117,
                        "elevation": [],
                        "exit": null,
                        "lat": 41.1083549,
                        "lon": -8.5064236,
                        "relativeDirection": "DEPART",
                        "stayOn": false,
                        "streetName": "road"
                    },
                    {
                        "absoluteDirection": "NORTH",
                        "alerts": null,
                        "area": false,
                        "bogusName": false,
                        "distance": 596.6441280725147,
                        "elevation": [],
                        "exit": null,
                        "lat": 41.1090142,
                        "lon": -8.5100411,
                        "relativeDirection": "RIGHT",
                        "stayOn": false,
                        "streetName": "Rua de Santa Cruz"
                    },
                    {
                        "absoluteDirection": "NORTHWEST",
                        "alerts": null,
                        "area": false,
                        "bogusName": true,
                        "distance": 1906.0585083130406,
                        "elevation": [],
                        "exit": null,
                        "lat": 41.1142223,
                        "lon": -8.5105953,
                        "relativeDirection": "LEFT",
                        "stayOn": false,
                        "streetName": "road"
                    },
                    {
                        "absoluteDirection": "NORTH",
                        "alerts": null,
                        "area": false,
                        "bogusName": false,
                        "distance": 283.98605309680187,
                        "elevation": [],
                        "exit": null,
                        "lat": 41.1266651,
                        "lon": -8.5226139,
                        "relativeDirection": "CONTINUE",
                        "stayOn": false,
                        "streetName": "Rua Professor Camilo de Oliveira"
                    },
                    {
                        "absoluteDirection": "NORTHWEST",
                        "alerts": null,
                        "area": false,
                        "bogusName": false,
                        "distance": 111.94423896440736,
                        "elevation": [],
                        "exit": null,
                        "lat": 41.1290497,
                        "lon": -8.523701,
                        "relativeDirection": "CONTINUE",
                        "stayOn": false,
                        "streetName": "Rua D. JoÃ£o de FranÃ§a"
                    },
                    {
                        "absoluteDirection": "NORTHWEST",
                        "alerts": null,
                        "area": false,
                        "bogusName": false,
                        "distance": 792.6448862940912,
                        "elevation": [],
                        "exit": null,
                        "lat": 41.1298094,
                        "lon": -8.5245539,
                        "relativeDirection": "SLIGHTLY_RIGHT",
                        "stayOn": true,
                        "streetName": "Rua D. JoÃ£o de FranÃ§a"
                    },
                    {
                        "absoluteDirection": "NORTHWEST",
                        "alerts": null,
                        "area": false,
                        "bogusName": true,
                        "distance": 37.907518125025675,
                        "elevation": [],
                        "exit": null,
                        "lat": 41.1359527,
                        "lon": -8.5290224,
                        "relativeDirection": "CONTINUE",
                        "stayOn": false,
                        "streetName": "road"
                    },
                    {
                        "absoluteDirection": "WEST",
                        "alerts": null,
                        "area": false,
                        "bogusName": true,
                        "distance": 17.185633204920215,
                        "elevation": [],
                        "exit": "2",
                        "lat": 41.1361174,
                        "lon": -8.5294179,
                        "relativeDirection": "CIRCLE_CLOCKWISE",
                        "stayOn": false,
                        "streetName": "road"
                    },
                    {
                        "absoluteDirection": "NORTH",
                        "alerts": null,
                        "area": false,
                        "bogusName": false,
                        "distance": 30.81975595226748,
                        "elevation": [],
                        "exit": null,
                        "lat": 41.1361898,
                        "lon": -8.5295585,
                        "relativeDirection": "CONTINUE",
                        "stayOn": false,
                        "streetName": "Largo de Santo AntÃ³nio"
                    },
                    {
                        "absoluteDirection": "WEST",
                        "alerts": null,
                        "area": false,
                        "bogusName": false,
                        "distance": 88.01465492470926,
                        "elevation": [],
                        "exit": null,
                        "lat": 41.1364086,
                        "lon": -8.5297642,
                        "relativeDirection": "SLIGHTLY_LEFT",
                        "stayOn": true,
                        "streetName": "Largo de Santo AntÃ³nio"
                    }
                ],
                "to": {
                    "arrival": 1463524199000,
                    "departure": 1463524200000,
                    "lat": 41.1363545326431,
                    "lon": -8.530809970281682,
                    "name": "GONDOMAR (SOUTO)",
                    "orig": null,
                    "platformCode": null,
                    "stopCode": null,
                    "stopId": {
                        "agencyId": "22",
                        "id": "20307"
                    },
                    "stopIndex": null,
                    "zoneId": null
                },
                "transitLeg": false,
                "tripBlockId": null,
                "tripId": null,
                "tripShortName": null
            },
            {
                "agencyId": "22",
                "agencyName": "STCP",
                "agencyTimeZoneOffset": 3600000,
                "agencyUrl": "http://www.STCP.pt",
                "alerts": null,
                "alightRule": null,
                "arrivalDelay": 0,
                "boardRule": null,
                "departureDelay": 0,
                "distance": 6398.8693865282,
                "duration": 1104,
                "endTime": 1463525304000,
                "from": {
                    "arrival": 1463524199000,
                    "departure": 1463524200000,
                    "lat": 41.1363694326,
                    "lon": -8.53081083638,
                    "name": "GONDOMAR (SOUTO)",
                    "orig": null,
                    "platformCode": null,
                    "stopCode": null,
                    "stopId": {
                        "agencyId": "22",
                        "id": "20307"
                    },
                    "stopIndex": 0,
                    "zoneId": null
                },
                "headsign": null,
                "headway": null,
                "interlineWithPreviousLeg": false,
                "intermediateStops": null,
                "isNonExactFrequency": null,
                "legGeometry": {
                    "length": 309,
                    "levels": null,
                    "points": "emazFpdas@A]KBU?QBm@DaBLaCPg@Dg@BUDmAnBC@QNKFCBIDg@HM?cDhAI@UJIBCBMDKBsAj@o@Ti@?e@A_BFA?}@@G?a@@wAD]Am@EYUY[?HA??DGBE?C?CGCAC?I?YIYEQEA?mCe@cC[KAwBUa@IA?A?]GeAOyC_@BICMGIICG?I?EBEHCHoEi@_CYqBUC?UG[EMCYEqEi@u@K?AKAWEmEi@eBSoAOS}DEe@MREjCCH?J_@Ak@I]M\\Lj@H^@?KBIDkCLSDd@R|DSEk@EkAQUCEAYCwBYgAOaAMcCYGAK?IC_@K?AsBk@}C{@oBi@a@NUXC@?@WVc@`@CFQh@EHiAxCk@xAy@zBEJGNCBi@hAGnA?tCMxAWt@KZDeA@O@??gAAe@]kCMWc@WoA_@W?]EOK_@g@_@QSc@Ki@U_@T^Jh@Rb@^P^f@NJ\\DV?nA^b@VLV\\jC@d@AfAANEdAUr@]bAERq@|As@bASZ_@hAO`@Qf@Up@Tq@Pc@?CNa@^iAR[r@cAp@}Aq@|As@bASZ_@hAO`@Qf@Up@uAxEc@bBOtAIbAU`AA@u@xCDDBF?FCHEBEDE?GToA`F?DA?Sx@mB|H?@]rAI`@]tAIb@KZWbAu@tC[pA?BA?U`AWfAGTK\\_@fAuA`EUn@ADA@Wv@m@|AUr@GVuArDy@xBWt@ADABA@ENK`@Mn@Ih@AHEt@Cn@Bn@BvALnD?@Bh@DhA?JB\\BnAL~DNrEHlCAZAVOv@?DA@Kh@q@hDQn@x@~@f@z@b@jAx@`Ct@zB??BBRn@Nh@|@jDLh@Rp@bB|GV`ByA`AW^}AtFKn@CR@d@@B?N?XCpDB`@F^HPfAZ"
                },
                "mode": "BUS",
                "notes": null,
                "realTime": false,
                "rentedBike": false,
                "route": "800",
                "routeColor": null,
                "routeId": "2043",
                "routeLongName": "BOLHÃƒO - MERCADO (Desc)",
                "routeShortName": "800",
                "routeTextColor": null,
                "routeType": 3,
                "serviceDate": "20160517",
                "startTime": 1463524200000,
                "steps": [],
                "to": {
                    "arrival": 1463525304000,
                    "departure": 1463525305000,
                    "lat": 41.1671544704,
                    "lon": -8.57045421785,
                    "name": "S.ROQUE G. BARROS",
                    "orig": null,
                    "platformCode": null,
                    "stopCode": null,
                    "stopId": {
                        "agencyId": "22",
                        "id": "26300"
                    },
                    "stopIndex": 23,
                    "zoneId": null
                },
                "transitLeg": true,
                "tripBlockId": null,
                "tripId": "119312",
                "tripShortName": null
            },
            {
                "agencyId": null,
                "agencyName": null,
                "agencyTimeZoneOffset": 3600000,
                "agencyUrl": null,
                "alerts": null,
                "alightRule": null,
                "arrivalDelay": 0,
                "boardRule": null,
                "departureDelay": 0,
                "distance": 23.556266651343392,
                "duration": 18,
                "endTime": 1463525323000,
                "from": {
                    "arrival": 1463525304000,
                    "departure": 1463525305000,
                    "lat": 41.16712951776034,
                    "lon": -8.570393893803276,
                    "name": "S.ROQUE G. BARROS",
                    "orig": null,
                    "platformCode": null,
                    "stopCode": null,
                    "stopId": {
                        "agencyId": "22",
                        "id": "26300"
                    },
                    "stopIndex": null,
                    "zoneId": null
                },
                "headsign": null,
                "headway": null,
                "interlineWithPreviousLeg": false,
                "intermediateStops": null,
                "isNonExactFrequency": null,
                "legGeometry": {
                    "length": 2,
                    "levels": null,
                    "points": "omgzF~{hs@f@N"
                },
                "mode": "WALK",
                "notes": null,
                "realTime": false,
                "rentedBike": false,
                "route": "",
                "routeColor": null,
                "routeId": null,
                "routeLongName": null,
                "routeShortName": null,
                "routeTextColor": null,
                "routeType": null,
                "serviceDate": null,
                "startTime": 1463525305000,
                "steps": [
                    {
                        "absoluteDirection": "SOUTH",
                        "alerts": null,
                        "area": false,
                        "bogusName": false,
                        "distance": 23.556266651343392,
                        "elevation": [],
                        "exit": null,
                        "lat": 41.16712951776034,
                        "lon": -8.570393893803276,
                        "relativeDirection": "DEPART",
                        "stayOn": false,
                        "streetName": "R. de Gama Barros"
                    }
                ],
                "to": {
                    "arrival": 1463525323000,
                    "departure": 1463526000000,
                    "lat": 41.16692725080269,
                    "lon": -8.570477560181512,
                    "name": "S. ROQUE G. BARROS",
                    "orig": null,
                    "platformCode": null,
                    "stopCode": null,
                    "stopId": {
                        "agencyId": "22",
                        "id": "22005"
                    },
                    "stopIndex": null,
                    "zoneId": null
                },
                "transitLeg": false,
                "tripBlockId": null,
                "tripId": null,
                "tripShortName": null
            },
            {
                "agencyId": "22",
                "agencyName": "STCP",
                "agencyTimeZoneOffset": 3600000,
                "agencyUrl": "http://www.STCP.pt",
                "alerts": null,
                "alightRule": null,
                "arrivalDelay": 0,
                "boardRule": null,
                "departureDelay": 0,
                "distance": 4154.53864948285,
                "duration": 1020,
                "endTime": 1463527020000,
                "from": {
                    "arrival": 1463525323000,
                    "departure": 1463526000000,
                    "lat": 41.1669376486,
                    "lon": -8.57050269729,
                    "name": "S. ROQUE G. BARROS",
                    "orig": null,
                    "platformCode": null,
                    "stopCode": null,
                    "stopId": {
                        "agencyId": "22",
                        "id": "22005"
                    },
                    "stopIndex": 0,
                    "zoneId": null
                },
                "headsign": null,
                "headway": null,
                "interlineWithPreviousLeg": false,
                "intermediateStops": null,
                "isNonExactFrequency": null,
                "legGeometry": {
                    "length": 210,
                    "levels": null,
                    "points": "clgzFp|hs@f@NDdADlA@rBFtC@XFbED|A@HFdC?VBp@Cq@?W?VBp@@xCBp@FNFBzAIVMfBlBQZU\\KCI?I?I@IFGDEJEHCL?L?JBNC`@?FGRe@z@A@EFEHwA{AGJELARdArAN?b@j@JLAF@GGICCc@k@O?eAsAAt@@Pn@v@H?FKp@z@e@x@_@]{@s@WG]EE?CA?AICe@SUGBLA^Mr@K^]j@SZOXWDe@DS?R?d@EVEd@@b@Br@Ph@Rr@d@b@b@lBlCHTIZ[j@u@tA[p@{@`@c@NI?wAc@YMg@a@m@e@o@h@?V?\\An@??QjEOhFqAi@EA}Ao@{Ak@i@pCc@~Ba@|BUnAGTdEbB@@fBr@\\NbAb@~B`AnBj@lBt@t@V~Bn@PBt@Pt@`@bAV??lBh@LHMImBi@cAWu@a@t@`@bAVlBh@LHjAz@`At@`BrAn@f@h@h@d@d@e@e@i@i@o@g@??aBsAaAu@`At@`BrAn@f@h@h@d@d@JHf@b@bAx@t@l@b@ZrB|AVxAj@bDC^A@MbBy@|Me@zHInA?@g@`If@cIHoAInAg@bI_@pGo@`IQ|BP{B?An@aIo@`IQ|BEn@CV?^UhDe@vHKbCA@i@vIj@yIJcCKbCk@xIYxDW~DV}D"
                },
                "mode": "BUS",
                "notes": null,
                "realTime": false,
                "rentedBike": false,
                "route": "402",
                "routeColor": null,
                "routeId": "1253",
                "routeLongName": "BOAVISTA - B. SUCESSO (Desc)",
                "routeShortName": "402",
                "routeTextColor": null,
                "routeType": 3,
                "serviceDate": "20160518",
                "startTime": 1463526000000,
                "steps": [],
                "to": {
                    "arrival": 1463527020000,
                    "departure": 1463527021000,
                    "lat": 41.1626761721,
                    "lon": -8.6101501472,
                    "name": "ANTERO DE QUENTAL",
                    "orig": null,
                    "platformCode": null,
                    "stopCode": null,
                    "stopId": {
                        "agencyId": "22",
                        "id": "21392"
                    },
                    "stopIndex": 14,
                    "zoneId": null
                },
                "transitLeg": true,
                "tripBlockId": null,
                "tripId": "113948",
                "tripShortName": null
            },
            {
                "agencyId": null,
                "agencyName": null,
                "agencyTimeZoneOffset": 3600000,
                "agencyUrl": null,
                "alerts": null,
                "alightRule": null,
                "arrivalDelay": 0,
                "boardRule": null,
                "departureDelay": 0,
                "distance": 986.3087071276133,
                "duration": 762,
                "endTime": 1463527783000,
                "from": {
                    "arrival": 1463527020000,
                    "departure": 1463527021000,
                    "lat": 41.16258269402105,
                    "lon": -8.61016290229128,
                    "name": "ANTERO DE QUENTAL",
                    "orig": null,
                    "platformCode": null,
                    "stopCode": null,
                    "stopId": {
                        "agencyId": "22",
                        "id": "21392"
                    },
                    "stopIndex": null,
                    "zoneId": null
                },
                "headsign": null,
                "headway": null,
                "interlineWithPreviousLeg": false,
                "intermediateStops": null,
                "isNonExactFrequency": null,
                "legGeometry": {
                    "length": 16,
                    "levels": null,
                    "points": "cqfzFptps@Y~Dy@G}AEwEKwACeFzAKD{@VeB\\]NoA^cDfAA?qGyHgAsA"
                },
                "mode": "WALK",
                "notes": null,
                "realTime": false,
                "rentedBike": false,
                "route": "",
                "routeColor": null,
                "routeId": null,
                "routeLongName": null,
                "routeShortName": null,
                "routeTextColor": null,
                "routeType": null,
                "serviceDate": null,
                "startTime": 1463527021000,
                "steps": [
                    {
                        "absoluteDirection": "WEST",
                        "alerts": null,
                        "area": false,
                        "bogusName": false,
                        "distance": 82.24329268498037,
                        "elevation": [],
                        "exit": null,
                        "lat": 41.16258269402105,
                        "lon": -8.61016290229128,
                        "relativeDirection": "DEPART",
                        "stayOn": false,
                        "streetName": "Rua da ConstituiÃ§Ã£o"
                    },
                    {
                        "absoluteDirection": "NORTH",
                        "alerts": null,
                        "area": false,
                        "bogusName": false,
                        "distance": 253.43184865829693,
                        "elevation": [],
                        "exit": null,
                        "lat": 41.1627146,
                        "lon": -8.6111296,
                        "relativeDirection": "RIGHT",
                        "stayOn": false,
                        "streetName": "Rua de Antero de Quental"
                    },
                    {
                        "absoluteDirection": "NORTH",
                        "alerts": null,
                        "area": false,
                        "bogusName": false,
                        "distance": 395.6219719388332,
                        "elevation": [],
                        "exit": null,
                        "lat": 41.1649902,
                        "lon": -8.6109751,
                        "relativeDirection": "SLIGHTLY_LEFT",
                        "stayOn": false,
                        "streetName": "Rua do Vale Formoso"
                    },
                    {
                        "absoluteDirection": "NORTHEAST",
                        "alerts": null,
                        "area": false,
                        "bogusName": false,
                        "distance": 255.0115938455029,
                        "elevation": [],
                        "exit": null,
                        "lat": 41.1683952,
                        "lon": -8.6123373,
                        "relativeDirection": "RIGHT",
                        "stayOn": false,
                        "streetName": "Rua Professor Joaquim Bastos"
                    }
                ],
                "to": {
                    "arrival": 1463527783000,
                    "departure": null,
                    "lat": 41.17012963771876,
                    "lon": -8.610344089436168,
                    "name": "Rua Professor Joaquim Bastos",
                    "orig": "",
                    "platformCode": null,
                    "stopCode": null,
                    "stopId": null,
                    "stopIndex": null,
                    "zoneId": null
                },
                "transitLeg": false,
                "tripBlockId": null,
                "tripId": null,
                "tripShortName": null
            }
        ],
        "startTime": 1463520943000,
        "tooSloped": false,
        "transfers": 1,
        "transitTime": 2124,
        "waitingTime": 680,
        "walkDistance": 5253.21868726112,
        "walkLimitExceeded": false,
        "walkTime": 4036
    },
    {
        "duration": 5730,
        "elevationGained": 0,
        "elevationLost": 0,
        "endTime": 1463530273000,
        "fare": null,
        "legs": [
            {
                "agencyId": null,
                "agencyName": null,
                "agencyTimeZoneOffset": 3600000,
                "agencyUrl": null,
                "alerts": null,
                "alightRule": null,
                "arrivalDelay": 0,
                "boardRule": null,
                "departureDelay": 0,
                "distance": 4242.94807439751,
                "duration": 3256,
                "endTime": 1463527799000,
                "from": {
                    "arrival": null,
                    "departure": 1463524543000,
                    "lat": 41.1083549,
                    "lon": -8.5064236,
                    "name": "road",
                    "orig": "",
                    "platformCode": null,
                    "stopCode": null,
                    "stopId": null,
                    "stopIndex": null,
                    "zoneId": null
                },
                "headsign": null,
                "headway": null,
                "interlineWithPreviousLeg": false,
                "intermediateStops": null,
                "isNonExactFrequency": null,
                "legGeometry": {
                    "length": 138,
                    "levels": null,
                    "points": "e~{yFdl|r@MR[JaANw@PKPIh@?T@v@AjADf@Jx@\\dALd@Fr@?v@Ev@IhA_I`Ba@AWAoEyA}@AiEtAm@N]@sBBUr@_@bBCh@GlBIXWb@iAhBoAhFcAn@Gp@KxAQ`@iCtGKb@Od@UX}@j@C@mAx@Q\\Eh@@RE?CBCDAF?FYFcA?m@Bo@JeAPo@Pg@Xc@Za@@_@EiAYq@Mu@Ke@A_@@GDa@b@aAn@s@h@WTSp@a@hBUp@OPUB_@F]DYP_@^e@r@_@Z]Ja@Aa@?c@Bc@VyBvAwA|@qAr@}@Zq@VODoATiB^sAXsBv@iAjAKJU\\a@Vi@b@i@bA[NcEnBqAr@qAx@YRm@t@Yp@EFaAnAc@ZgDtBiEhAoA\\oAr@m@`Ao@r@KVQn@M\\?F?DADABA@C@C?SFOPGNCTJzC@\\"
                },
                "mode": "WALK",
                "notes": null,
                "realTime": false,
                "rentedBike": false,
                "route": "",
                "routeColor": null,
                "routeId": null,
                "routeLongName": null,
                "routeShortName": null,
                "routeTextColor": null,
                "routeType": null,
                "serviceDate": null,
                "startTime": 1463524543000,
                "steps": [
                    {
                        "absoluteDirection": "NORTHWEST",
                        "alerts": null,
                        "area": false,
                        "bogusName": false,
                        "distance": 377.74269744973117,
                        "elevation": [],
                        "exit": null,
                        "lat": 41.1083549,
                        "lon": -8.5064236,
                        "relativeDirection": "DEPART",
                        "stayOn": false,
                        "streetName": "road"
                    },
                    {
                        "absoluteDirection": "NORTH",
                        "alerts": null,
                        "area": false,
                        "bogusName": false,
                        "distance": 596.6441280725147,
                        "elevation": [],
                        "exit": null,
                        "lat": 41.1090142,
                        "lon": -8.5100411,
                        "relativeDirection": "RIGHT",
                        "stayOn": false,
                        "streetName": "Rua de Santa Cruz"
                    },
                    {
                        "absoluteDirection": "NORTHWEST",
                        "alerts": null,
                        "area": false,
                        "bogusName": true,
                        "distance": 1906.0585083130406,
                        "elevation": [],
                        "exit": null,
                        "lat": 41.1142223,
                        "lon": -8.5105953,
                        "relativeDirection": "LEFT",
                        "stayOn": false,
                        "streetName": "road"
                    },
                    {
                        "absoluteDirection": "NORTH",
                        "alerts": null,
                        "area": false,
                        "bogusName": false,
                        "distance": 283.98605309680187,
                        "elevation": [],
                        "exit": null,
                        "lat": 41.1266651,
                        "lon": -8.5226139,
                        "relativeDirection": "CONTINUE",
                        "stayOn": false,
                        "streetName": "Rua Professor Camilo de Oliveira"
                    },
                    {
                        "absoluteDirection": "NORTHWEST",
                        "alerts": null,
                        "area": false,
                        "bogusName": false,
                        "distance": 111.94423896440736,
                        "elevation": [],
                        "exit": null,
                        "lat": 41.1290497,
                        "lon": -8.523701,
                        "relativeDirection": "CONTINUE",
                        "stayOn": false,
                        "streetName": "Rua D. JoÃ£o de FranÃ§a"
                    },
                    {
                        "absoluteDirection": "NORTHWEST",
                        "alerts": null,
                        "area": false,
                        "bogusName": false,
                        "distance": 792.6448862940912,
                        "elevation": [],
                        "exit": null,
                        "lat": 41.1298094,
                        "lon": -8.5245539,
                        "relativeDirection": "SLIGHTLY_RIGHT",
                        "stayOn": true,
                        "streetName": "Rua D. JoÃ£o de FranÃ§a"
                    },
                    {
                        "absoluteDirection": "NORTHWEST",
                        "alerts": null,
                        "area": false,
                        "bogusName": true,
                        "distance": 37.907518125025675,
                        "elevation": [],
                        "exit": null,
                        "lat": 41.1359527,
                        "lon": -8.5290224,
                        "relativeDirection": "CONTINUE",
                        "stayOn": false,
                        "streetName": "road"
                    },
                    {
                        "absoluteDirection": "WEST",
                        "alerts": null,
                        "area": false,
                        "bogusName": true,
                        "distance": 17.185633204920215,
                        "elevation": [],
                        "exit": "2",
                        "lat": 41.1361174,
                        "lon": -8.5294179,
                        "relativeDirection": "CIRCLE_CLOCKWISE",
                        "stayOn": false,
                        "streetName": "road"
                    },
                    {
                        "absoluteDirection": "NORTH",
                        "alerts": null,
                        "area": false,
                        "bogusName": false,
                        "distance": 30.81975595226748,
                        "elevation": [],
                        "exit": null,
                        "lat": 41.1361898,
                        "lon": -8.5295585,
                        "relativeDirection": "CONTINUE",
                        "stayOn": false,
                        "streetName": "Largo de Santo AntÃ³nio"
                    },
                    {
                        "absoluteDirection": "WEST",
                        "alerts": null,
                        "area": false,
                        "bogusName": false,
                        "distance": 88.01465492470926,
                        "elevation": [],
                        "exit": null,
                        "lat": 41.1364086,
                        "lon": -8.5297642,
                        "relativeDirection": "SLIGHTLY_LEFT",
                        "stayOn": true,
                        "streetName": "Largo de Santo AntÃ³nio"
                    }
                ],
                "to": {
                    "arrival": 1463527799000,
                    "departure": 1463527800000,
                    "lat": 41.1363545326431,
                    "lon": -8.530809970281682,
                    "name": "GONDOMAR (SOUTO)",
                    "orig": null,
                    "platformCode": null,
                    "stopCode": null,
                    "stopId": {
                        "agencyId": "22",
                        "id": "20307"
                    },
                    "stopIndex": null,
                    "zoneId": null
                },
                "transitLeg": false,
                "tripBlockId": null,
                "tripId": null,
                "tripShortName": null
            },
            {
                "agencyId": "22",
                "agencyName": "STCP",
                "agencyTimeZoneOffset": 3600000,
                "agencyUrl": "http://www.STCP.pt",
                "alerts": null,
                "alightRule": null,
                "arrivalDelay": 0,
                "boardRule": null,
                "departureDelay": 0,
                "distance": 8740.668824457856,
                "duration": 1039,
                "endTime": 1463528839000,
                "from": {
                    "arrival": 1463527799000,
                    "departure": 1463527800000,
                    "lat": 41.1363694326,
                    "lon": -8.53081083638,
                    "name": "GONDOMAR (SOUTO)",
                    "orig": null,
                    "platformCode": null,
                    "stopCode": null,
                    "stopId": {
                        "agencyId": "22",
                        "id": "20307"
                    },
                    "stopIndex": 0,
                    "zoneId": null
                },
                "headsign": null,
                "headway": null,
                "interlineWithPreviousLeg": false,
                "intermediateStops": null,
                "isNonExactFrequency": null,
                "legGeometry": {
                    "length": 437,
                    "levels": null,
                    "points": "emazFpdas@A]KBU?QBm@DaBLaCPg@Dg@BUDmAnBC@QNKFCBIDg@HM?cDhAI@UJIBCBMDKBsAj@o@Ti@?e@A_BFA?}@@G?a@@wAD]Am@EYUY[?HA??DGBE?C?CGCAC?I?YIYEQEA?mCe@cC[KAwBUa@IA?A?]GeAOyC_@BICMGIICG?I?EBEHCHoEi@_CYqBUC?UG[EMCYEqEi@u@K?AKAWEmEi@eBSoAOS}DEe@MREjCCH?J_@Ak@I]M\\Lj@H^@?KBIDkCLSDd@R|DSEk@EkAQUCEAYCwBYgAOaAMcCYGAK?IC_@K?AsBk@}C{@oBi@a@NUXC@?@WVc@`@CFQh@EHiAxCk@xAy@zBEJGNCBi@hAGnA?tCMxAWt@KZDeA@O@??gAAe@]kCMWc@WoA_@W?]EOK_@g@_@QSc@Ki@U_@T^Jh@Rb@^P^f@NJ\\DV?nA^b@VLV\\jC@d@AfAANEdAUr@]bAERq@|As@bASZ_@hAO`@Qf@Up@Tq@Pc@?CNa@^iAR[r@cAp@}Aq@|As@bASZ_@hAO`@Qf@Up@uAxEc@bBOtAIbAU`AA@u@xCDDBF?FCHEBEDE?GToA`F?DA?Sx@mB|H?@]rAI`@]tAIb@KZWbAu@tC[pA?BA?U`AWfAGTK\\_@fAuA`EUn@ADA@Wv@m@|AUr@GVuArDy@xBWt@ADABA@ENK`@Mn@Ih@AHEt@Cn@Bn@BvALnD?@Bh@DhA?JB\\BnAL~DNrEHlCAZAVOv@?DA@Kh@q@hDQn@x@~@f@z@b@jAx@`Ct@zB??BBRn@Nh@|@jDLh@Rp@bB|GV`BHZJ^Dn@?~A???_BEo@K_@I[yA`AW^}AtFKn@CRBh@?N?X??CpD?XEf@GZO\\[XYJi@@oBQeD[YEYKSWUa@Mc@YaA}@_D_BqF[k@c@c@b@b@Zj@~ApF@?z@~C}@_D_BqF[k@c@c@WM_@Ie@?e@H]J}@Z{Af@A@e@NUPKBQ?P?JCTQf@QzAg@{Af@g@PUPKBQ?MCMBO@IHQFK@WG]M[WuA_BIMHLKIIIkAqAa@o@a@c@YS[IYF[PaAvAuEhHADuB|CaAxA}A|B{@~@QJWBO?QBMLIR?TI\\[h@Qb@Or@Gl@CPAf@?z@DtHIz@Gf@Mf@Up@Tq@Lg@Fg@H{@EuH???{@@g@Af@?z@DtHIz@Gf@Mf@Up@Qd@{A`EOn@Gx@BfA@Z?@@R?l@nAlW"
                },
                "mode": "BUS",
                "notes": null,
                "realTime": false,
                "rentedBike": false,
                "route": "9M",
                "routeColor": null,
                "routeId": "2002",
                "routeLongName": "ROT. A.E.P. (Desc)",
                "routeShortName": "9M",
                "routeTextColor": null,
                "routeType": 3,
                "serviceDate": "20160518",
                "startTime": 1463527800000,
                "steps": [],
                "to": {
                    "arrival": 1463528839000,
                    "departure": 1463528880000,
                    "lat": 41.1806451347,
                    "lon": -8.58119524841,
                    "name": "ROT. DA AREOSA",
                    "orig": null,
                    "platformCode": null,
                    "stopCode": null,
                    "stopId": {
                        "agencyId": "22",
                        "id": "22384"
                    },
                    "stopIndex": 30,
                    "zoneId": null
                },
                "transitLeg": true,
                "tripBlockId": null,
                "tripId": "120371",
                "tripShortName": null
            },
            {
                "agencyId": "22",
                "agencyName": "STCP",
                "agencyTimeZoneOffset": 3600000,
                "agencyUrl": "http://www.STCP.pt",
                "alerts": null,
                "alightRule": null,
                "arrivalDelay": 0,
                "boardRule": null,
                "departureDelay": 0,
                "distance": 4776.375734471943,
                "duration": 555,
                "endTime": 1463529435000,
                "from": {
                    "arrival": 1463528839000,
                    "departure": 1463528880000,
                    "lat": 41.1806451347,
                    "lon": -8.58119524841,
                    "name": "ROT. DA AREOSA",
                    "orig": null,
                    "platformCode": null,
                    "stopCode": null,
                    "stopId": {
                        "agencyId": "22",
                        "id": "22384"
                    },
                    "stopIndex": 24,
                    "zoneId": null
                },
                "headsign": null,
                "headway": null,
                "interlineWithPreviousLeg": false,
                "intermediateStops": null,
                "isNonExactFrequency": null,
                "legGeometry": {
                    "length": 184,
                    "levels": null,
                    "points": "qajzFl_ks@??Dz@?X?h@FKLEJ?JFFLXTvBd@t@NpBz@|D~@rAj@??lIjDpAp@T@zCjAnAh@@?j@TbEbBpChAz@Z??JDLF@L`Bn@fBv@dEbB@@fBr@\\NbAb@~B`AnBj@lBt@t@V~Bn@PBt@Pt@`@bAV??lBh@LHMImBi@cAWu@a@t@`@bAVlBh@LHjAz@`At@`BrAn@f@h@h@d@d@e@e@i@i@o@g@??aBsAaAu@`At@`BrAn@f@h@h@d@d@JHf@b@bAx@t@l@b@ZfAHXB\\NdAh@`@P?@tAp@sAo@ACa@Q`@PtAr@rBbAvB~@B@fDbB`@Tx@`@dCfAHDIEeCgACC??u@]x@`@dCfAHDx@ZjAn@f@Xz@b@fAf@@?z@`@lB|@hAj@n@XbAh@|@b@nAl@^Pb@T`CnA??FBGCaCoA`CnAFB|DtBvAh@VNtDdBBR@ZZ]PKB?@AnAo@LKB\\?Zc@nDa@pDe@zDOnANmA?Ad@{De@zDOnAG`@e@xEk@vDS~AAFCJ?DId@??U`BQnAoCu@{A]kDaAu@hEg@xC?HCDGCKEKhBc@fCGjAxAfB@B@NBZf@f@nBBf@N?G"
                },
                "mode": "BUS",
                "notes": null,
                "realTime": false,
                "rentedBike": false,
                "route": "8M",
                "routeColor": null,
                "routeId": "1996",
                "routeLongName": "AV.ALIADOS (Desc)",
                "routeShortName": "8M",
                "routeTextColor": null,
                "routeType": 3,
                "serviceDate": "20160518",
                "startTime": 1463528880000,
                "steps": [],
                "to": {
                    "arrival": 1463529435000,
                    "departure": 1463529436000,
                    "lat": 41.1512427742,
                    "lon": -8.6094696395,
                    "name": "TRINDADE",
                    "orig": null,
                    "platformCode": null,
                    "stopCode": null,
                    "stopId": {
                        "agencyId": "22",
                        "id": "22353"
                    },
                    "stopIndex": 38,
                    "zoneId": null
                },
                "transitLeg": true,
                "tripBlockId": null,
                "tripId": "119144",
                "tripShortName": null
            },
            {
                "agencyId": null,
                "agencyName": null,
                "agencyTimeZoneOffset": 3600000,
                "agencyUrl": null,
                "alerts": null,
                "alightRule": null,
                "arrivalDelay": 0,
                "boardRule": null,
                "departureDelay": 0,
                "distance": 52.471731385410536,
                "duration": 42,
                "endTime": 1463529478000,
                "from": {
                    "arrival": 1463529435000,
                    "departure": 1463529436000,
                    "lat": 41.15127546620941,
                    "lon": -8.60943102181194,
                    "name": "TRINDADE",
                    "orig": null,
                    "platformCode": null,
                    "stopCode": null,
                    "stopId": {
                        "agencyId": "22",
                        "id": "22353"
                    },
                    "stopIndex": null,
                    "zoneId": null
                },
                "headsign": null,
                "headway": null,
                "interlineWithPreviousLeg": false,
                "intermediateStops": null,
                "isNonExactFrequency": null,
                "legGeometry": {
                    "length": 8,
                    "levels": null,
                    "points": "mjdzF~ops@A?UROGQHCBGFKJ"
                },
                "mode": "WALK",
                "notes": null,
                "realTime": false,
                "rentedBike": false,
                "route": "",
                "routeColor": null,
                "routeId": null,
                "routeLongName": null,
                "routeShortName": null,
                "routeTextColor": null,
                "routeType": null,
                "serviceDate": null,
                "startTime": 1463529436000,
                "steps": [
                    {
                        "absoluteDirection": "NORTHWEST",
                        "alerts": null,
                        "area": false,
                        "bogusName": false,
                        "distance": 16.289731692813195,
                        "elevation": [],
                        "exit": null,
                        "lat": 41.15127546620941,
                        "lon": -8.60943102181194,
                        "relativeDirection": "DEPART",
                        "stayOn": false,
                        "streetName": "parking aisle"
                    },
                    {
                        "absoluteDirection": "NORTH",
                        "alerts": null,
                        "area": false,
                        "bogusName": false,
                        "distance": 36.18199969259734,
                        "elevation": [],
                        "exit": null,
                        "lat": 41.151399,
                        "lon": -8.6095356,
                        "relativeDirection": "SLIGHTLY_RIGHT",
                        "stayOn": false,
                        "streetName": "Rua da Trindade"
                    }
                ],
                "to": {
                    "arrival": 1463529478000,
                    "departure": 1463529655000,
                    "lat": 41.1516838,
                    "lon": -8.6096613,
                    "name": "TRINDADE",
                    "orig": null,
                    "platformCode": null,
                    "stopCode": null,
                    "stopId": {
                        "agencyId": "22",
                        "id": "21521"
                    },
                    "stopIndex": null,
                    "zoneId": null
                },
                "transitLeg": false,
                "tripBlockId": null,
                "tripId": null,
                "tripShortName": null
            },
            {
                "agencyId": "22",
                "agencyName": "STCP",
                "agencyTimeZoneOffset": 3600000,
                "agencyUrl": "http://www.STCP.pt",
                "alerts": null,
                "alightRule": null,
                "arrivalDelay": 0,
                "boardRule": null,
                "departureDelay": 0,
                "distance": 2030.2145436348246,
                "duration": 385,
                "endTime": 1463530040000,
                "from": {
                    "arrival": 1463529478000,
                    "departure": 1463529655000,
                    "lat": 41.1517853995,
                    "lon": -8.60952492041,
                    "name": "TRINDADE",
                    "orig": null,
                    "platformCode": null,
                    "stopCode": null,
                    "stopId": {
                        "agencyId": "22",
                        "id": "21521"
                    },
                    "stopIndex": 1,
                    "zoneId": null
                },
                "headsign": null,
                "headway": null,
                "interlineWithPreviousLeg": false,
                "intermediateStops": null,
                "isNonExactFrequency": null,
                "legGeometry": {
                    "length": 75,
                    "levels": null,
                    "points": "smdzFppps@HLq@`AG?sCI}BG?eDK?A@CB??ABAxDUGQAa@?WIc@]c@c@A?CAKO[Wa@Mm@Ac@??vCGtH??ChAgBCmDC]??T?t@???`@?a@?u@?U?T?t@?`@g@^[Ke@MeBOiD}@kASgBYcBYeAQ??k@KuEm@iEm@y@E}AE??}BG{ACwAEeFzAKFE??@u@RcB\\_@NoA`@cDdAA?YJo@TE?"
                },
                "mode": "BUS",
                "notes": null,
                "realTime": false,
                "rentedBike": false,
                "route": "4M",
                "routeColor": null,
                "routeId": "1212",
                "routeLongName": "MAIA (Asc)",
                "routeShortName": "4M",
                "routeTextColor": null,
                "routeType": 3,
                "serviceDate": "20160518",
                "startTime": 1463529655000,
                "steps": [],
                "to": {
                    "arrival": 1463530040000,
                    "departure": 1463530041000,
                    "lat": 41.1688330019,
                    "lon": -8.61232304853,
                    "name": "C. SAÃšDE PARANHOS",
                    "orig": null,
                    "platformCode": null,
                    "stopCode": null,
                    "stopId": {
                        "agencyId": "22",
                        "id": "21102"
                    },
                    "stopIndex": 8,
                    "zoneId": null
                },
                "transitLeg": true,
                "tripBlockId": null,
                "tripId": "113225",
                "tripShortName": null
            },
            {
                "agencyId": null,
                "agencyName": null,
                "agencyTimeZoneOffset": 3600000,
                "agencyUrl": null,
                "alerts": null,
                "alightRule": null,
                "arrivalDelay": 0,
                "boardRule": null,
                "departureDelay": 0,
                "distance": 298.1752361575192,
                "duration": 232,
                "endTime": 1463530273000,
                "from": {
                    "arrival": 1463530040000,
                    "departure": 1463530041000,
                    "lat": 41.16876345601781,
                    "lon": -8.612490710893281,
                    "name": "C. SAÃšDE PARANHOS",
                    "orig": null,
                    "platformCode": null,
                    "stopCode": null,
                    "stopId": {
                        "agencyId": "22",
                        "id": "21102"
                    },
                    "stopIndex": null,
                    "zoneId": null
                },
                "headsign": null,
                "headway": null,
                "interlineWithPreviousLeg": false,
                "intermediateStops": null,
                "isNonExactFrequency": null,
                "legGeometry": {
                    "length": 5,
                    "levels": null,
                    "points": "wwgzFbcqs@n@SXKqGyHgAsA"
                },
                "mode": "WALK",
                "notes": null,
                "realTime": false,
                "rentedBike": false,
                "route": "",
                "routeColor": null,
                "routeId": null,
                "routeLongName": null,
                "routeShortName": null,
                "routeTextColor": null,
                "routeType": null,
                "serviceDate": null,
                "startTime": 1463530041000,
                "steps": [
                    {
                        "absoluteDirection": "SOUTH",
                        "alerts": null,
                        "area": false,
                        "bogusName": false,
                        "distance": 43.163642312016265,
                        "elevation": [],
                        "exit": null,
                        "lat": 41.16876345601781,
                        "lon": -8.612490710893281,
                        "relativeDirection": "DEPART",
                        "stayOn": false,
                        "streetName": "Rua do Vale Formoso"
                    },
                    {
                        "absoluteDirection": "NORTHEAST",
                        "alerts": null,
                        "area": false,
                        "bogusName": false,
                        "distance": 255.0115938455029,
                        "elevation": [],
                        "exit": null,
                        "lat": 41.1683952,
                        "lon": -8.6123373,
                        "relativeDirection": "HARD_LEFT",
                        "stayOn": false,
                        "streetName": "Rua Professor Joaquim Bastos"
                    }
                ],
                "to": {
                    "arrival": 1463530273000,
                    "departure": null,
                    "lat": 41.17012963771876,
                    "lon": -8.610344089436168,
                    "name": "Rua Professor Joaquim Bastos",
                    "orig": "",
                    "platformCode": null,
                    "stopCode": null,
                    "stopId": null,
                    "stopIndex": null,
                    "zoneId": null
                },
                "transitLeg": false,
                "tripBlockId": null,
                "tripId": null,
                "tripShortName": null
            }
        ],
        "startTime": 1463524543000,
        "tooSloped": false,
        "transfers": 2,
        "transitTime": 1979,
        "waitingTime": 221,
        "walkDistance": 4593.981508093381,
        "walkLimitExceeded": false,
        "walkTime": 3530
    },
    {
        "duration": 5730,
        "elevationGained": 0,
        "elevationLost": 0,
        "endTime": 1463533873000,
        "fare": null,
        "legs": [
            {
                "agencyId": null,
                "agencyName": null,
                "agencyTimeZoneOffset": 3600000,
                "agencyUrl": null,
                "alerts": null,
                "alightRule": null,
                "arrivalDelay": 0,
                "boardRule": null,
                "departureDelay": 0,
                "distance": 4242.94807439751,
                "duration": 3256,
                "endTime": 1463531399000,
                "from": {
                    "arrival": null,
                    "departure": 1463528143000,
                    "lat": 41.1083549,
                    "lon": -8.5064236,
                    "name": "road",
                    "orig": "",
                    "platformCode": null,
                    "stopCode": null,
                    "stopId": null,
                    "stopIndex": null,
                    "zoneId": null
                },
                "headsign": null,
                "headway": null,
                "interlineWithPreviousLeg": false,
                "intermediateStops": null,
                "isNonExactFrequency": null,
                "legGeometry": {
                    "length": 138,
                    "levels": null,
                    "points": "e~{yFdl|r@MR[JaANw@PKPIh@?T@v@AjADf@Jx@\\dALd@Fr@?v@Ev@IhA_I`Ba@AWAoEyA}@AiEtAm@N]@sBBUr@_@bBCh@GlBIXWb@iAhBoAhFcAn@Gp@KxAQ`@iCtGKb@Od@UX}@j@C@mAx@Q\\Eh@@RE?CBCDAF?FYFcA?m@Bo@JeAPo@Pg@Xc@Za@@_@EiAYq@Mu@Ke@A_@@GDa@b@aAn@s@h@WTSp@a@hBUp@OPUB_@F]DYP_@^e@r@_@Z]Ja@Aa@?c@Bc@VyBvAwA|@qAr@}@Zq@VODoATiB^sAXsBv@iAjAKJU\\a@Vi@b@i@bA[NcEnBqAr@qAx@YRm@t@Yp@EFaAnAc@ZgDtBiEhAoA\\oAr@m@`Ao@r@KVQn@M\\?F?DADABA@C@C?SFOPGNCTJzC@\\"
                },
                "mode": "WALK",
                "notes": null,
                "realTime": false,
                "rentedBike": false,
                "route": "",
                "routeColor": null,
                "routeId": null,
                "routeLongName": null,
                "routeShortName": null,
                "routeTextColor": null,
                "routeType": null,
                "serviceDate": null,
                "startTime": 1463528143000,
                "steps": [
                    {
                        "absoluteDirection": "NORTHWEST",
                        "alerts": null,
                        "area": false,
                        "bogusName": false,
                        "distance": 377.74269744973117,
                        "elevation": [],
                        "exit": null,
                        "lat": 41.1083549,
                        "lon": -8.5064236,
                        "relativeDirection": "DEPART",
                        "stayOn": false,
                        "streetName": "road"
                    },
                    {
                        "absoluteDirection": "NORTH",
                        "alerts": null,
                        "area": false,
                        "bogusName": false,
                        "distance": 596.6441280725147,
                        "elevation": [],
                        "exit": null,
                        "lat": 41.1090142,
                        "lon": -8.5100411,
                        "relativeDirection": "RIGHT",
                        "stayOn": false,
                        "streetName": "Rua de Santa Cruz"
                    },
                    {
                        "absoluteDirection": "NORTHWEST",
                        "alerts": null,
                        "area": false,
                        "bogusName": true,
                        "distance": 1906.0585083130406,
                        "elevation": [],
                        "exit": null,
                        "lat": 41.1142223,
                        "lon": -8.5105953,
                        "relativeDirection": "LEFT",
                        "stayOn": false,
                        "streetName": "road"
                    },
                    {
                        "absoluteDirection": "NORTH",
                        "alerts": null,
                        "area": false,
                        "bogusName": false,
                        "distance": 283.98605309680187,
                        "elevation": [],
                        "exit": null,
                        "lat": 41.1266651,
                        "lon": -8.5226139,
                        "relativeDirection": "CONTINUE",
                        "stayOn": false,
                        "streetName": "Rua Professor Camilo de Oliveira"
                    },
                    {
                        "absoluteDirection": "NORTHWEST",
                        "alerts": null,
                        "area": false,
                        "bogusName": false,
                        "distance": 111.94423896440736,
                        "elevation": [],
                        "exit": null,
                        "lat": 41.1290497,
                        "lon": -8.523701,
                        "relativeDirection": "CONTINUE",
                        "stayOn": false,
                        "streetName": "Rua D. JoÃ£o de FranÃ§a"
                    },
                    {
                        "absoluteDirection": "NORTHWEST",
                        "alerts": null,
                        "area": false,
                        "bogusName": false,
                        "distance": 792.6448862940912,
                        "elevation": [],
                        "exit": null,
                        "lat": 41.1298094,
                        "lon": -8.5245539,
                        "relativeDirection": "SLIGHTLY_RIGHT",
                        "stayOn": true,
                        "streetName": "Rua D. JoÃ£o de FranÃ§a"
                    },
                    {
                        "absoluteDirection": "NORTHWEST",
                        "alerts": null,
                        "area": false,
                        "bogusName": true,
                        "distance": 37.907518125025675,
                        "elevation": [],
                        "exit": null,
                        "lat": 41.1359527,
                        "lon": -8.5290224,
                        "relativeDirection": "CONTINUE",
                        "stayOn": false,
                        "streetName": "road"
                    },
                    {
                        "absoluteDirection": "WEST",
                        "alerts": null,
                        "area": false,
                        "bogusName": true,
                        "distance": 17.185633204920215,
                        "elevation": [],
                        "exit": "2",
                        "lat": 41.1361174,
                        "lon": -8.5294179,
                        "relativeDirection": "CIRCLE_CLOCKWISE",
                        "stayOn": false,
                        "streetName": "road"
                    },
                    {
                        "absoluteDirection": "NORTH",
                        "alerts": null,
                        "area": false,
                        "bogusName": false,
                        "distance": 30.81975595226748,
                        "elevation": [],
                        "exit": null,
                        "lat": 41.1361898,
                        "lon": -8.5295585,
                        "relativeDirection": "CONTINUE",
                        "stayOn": false,
                        "streetName": "Largo de Santo AntÃ³nio"
                    },
                    {
                        "absoluteDirection": "WEST",
                        "alerts": null,
                        "area": false,
                        "bogusName": false,
                        "distance": 88.01465492470926,
                        "elevation": [],
                        "exit": null,
                        "lat": 41.1364086,
                        "lon": -8.5297642,
                        "relativeDirection": "SLIGHTLY_LEFT",
                        "stayOn": true,
                        "streetName": "Largo de Santo AntÃ³nio"
                    }
                ],
                "to": {
                    "arrival": 1463531399000,
                    "departure": 1463531400000,
                    "lat": 41.1363545326431,
                    "lon": -8.530809970281682,
                    "name": "GONDOMAR (SOUTO)",
                    "orig": null,
                    "platformCode": null,
                    "stopCode": null,
                    "stopId": {
                        "agencyId": "22",
                        "id": "20307"
                    },
                    "stopIndex": null,
                    "zoneId": null
                },
                "transitLeg": false,
                "tripBlockId": null,
                "tripId": null,
                "tripShortName": null
            },
            {
                "agencyId": "22",
                "agencyName": "STCP",
                "agencyTimeZoneOffset": 3600000,
                "agencyUrl": "http://www.STCP.pt",
                "alerts": null,
                "alightRule": null,
                "arrivalDelay": 0,
                "boardRule": null,
                "departureDelay": 0,
                "distance": 5749.296888368897,
                "duration": 693,
                "endTime": 1463532093000,
                "from": {
                    "arrival": 1463531399000,
                    "departure": 1463531400000,
                    "lat": 41.1363694326,
                    "lon": -8.53081083638,
                    "name": "GONDOMAR (SOUTO)",
                    "orig": null,
                    "platformCode": null,
                    "stopCode": null,
                    "stopId": {
                        "agencyId": "22",
                        "id": "20307"
                    },
                    "stopIndex": 0,
                    "zoneId": null
                },
                "headsign": null,
                "headway": null,
                "interlineWithPreviousLeg": false,
                "intermediateStops": null,
                "isNonExactFrequency": null,
                "legGeometry": {
                    "length": 286,
                    "levels": null,
                    "points": "emazFpdas@A]KBU?QBm@DaBLaCPg@Dg@BUDmAnBC@QNKFCBIDg@HM?cDhAI@UJIBCBMDKBsAj@o@Ti@?e@A_BFA?}@@G?a@@wAD]Am@EYUY[?HA??DGBE?C?CGCAC?I?YIYEQEA?mCe@cC[KAwBUa@IA?A?]GeAOyC_@BICMGIICG?I?EBEHCHoEi@_CYqBUC?UG[EMCYEqEi@u@K?AKAWEmEi@eBSoAOS}DEe@MREjCCH?J_@Ak@I]M\\Lj@H^@?KBIDkCLSDd@R|DSEk@EkAQUCEAYCwBYgAOaAMcCYGAK?IC_@K?AsBk@}C{@oBi@a@NUXC@?@WVc@`@CFQh@EHiAxCk@xAy@zBEJGNCBi@hAGnA?tCMxAWt@KZDeA@O@??gAAe@]kCMWc@WoA_@W?]EOK_@g@_@QSc@Ki@U_@T^Jh@Rb@^P^f@NJ\\DV?nA^b@VLV\\jC@d@AfAANEdAUr@]bAERq@|As@bASZ_@hAO`@Qf@Up@Tq@Pc@?CNa@^iAR[r@cAp@}Aq@|As@bASZ_@hAO`@Qf@Up@uAxEc@bBOtAIbAU`AA@u@xCDDBF?FCHEBEDE?GToA`F?DA?Sx@mB|H?@]rAI`@]tAIb@KZWbAu@tC[pA?BA?U`AWfAGTK\\_@fAuA`EUn@ADA@Wv@m@|AUr@GVuArDy@xBWt@ADABA@ENK`@Mn@Ih@AHEt@Cn@Bn@BvALnD?@Bh@DhA?JB\\BnAL~DNrEHlCAZAVOv@?DA@Kh@q@hDQn@x@~@f@z@b@jAx@`Ct@zB"
                },
                "mode": "BUS",
                "notes": null,
                "realTime": false,
                "rentedBike": false,
                "route": "9M",
                "routeColor": null,
                "routeId": "2002",
                "routeLongName": "ROT. A.E.P. (Desc)",
                "routeShortName": "9M",
                "routeTextColor": null,
                "routeType": 3,
                "serviceDate": "20160518",
                "startTime": 1463531400000,
                "steps": [],
                "to": {
                    "arrival": 1463532093000,
                    "departure": 1463532246000,
                    "lat": 41.1678668396,
                    "lon": -8.56280434667,
                    "name": "MEIRAL",
                    "orig": null,
                    "platformCode": null,
                    "stopCode": null,
                    "stopId": {
                        "agencyId": "22",
                        "id": "20254"
                    },
                    "stopIndex": 21,
                    "zoneId": null
                },
                "transitLeg": true,
                "tripBlockId": null,
                "tripId": "120373",
                "tripShortName": null
            },
            {
                "agencyId": "22",
                "agencyName": "STCP",
                "agencyTimeZoneOffset": 3600000,
                "agencyUrl": "http://www.STCP.pt",
                "alerts": null,
                "alightRule": null,
                "arrivalDelay": 0,
                "boardRule": null,
                "departureDelay": 0,
                "distance": 4974.067909783787,
                "duration": 789,
                "endTime": 1463533035000,
                "from": {
                    "arrival": 1463532093000,
                    "departure": 1463532246000,
                    "lat": 41.1678668396,
                    "lon": -8.56280434667,
                    "name": "MEIRAL",
                    "orig": null,
                    "platformCode": null,
                    "stopCode": null,
                    "stopId": {
                        "agencyId": "22",
                        "id": "20254"
                    },
                    "stopIndex": 25,
                    "zoneId": null
                },
                "headsign": null,
                "headway": null,
                "interlineWithPreviousLeg": false,
                "intermediateStops": null,
                "isNonExactFrequency": null,
                "legGeometry": {
                    "length": 203,
                    "levels": null,
                    "points": "sqgzFdlgs@??BBRn@Nh@|@jDLh@Rp@bB|GV`ByA`AW^}AtFKn@CR@d@@B?N?XCpDB`@F^HPfAZ??j@Ph@Pf@Nt@Rr@Lb@PvD`A`Bd@rBpAj@^DJ\\v@?BZr@[s@]{@EKDJ\\z@Zr@Rn@h@|AvB|F@F`@dA@DDH@@p@nBr@rA^^T`@Nb@hBpE|@vBRj@Sk@}@wBACgBmEhBpE|@vBRj@J^|@zA`@n@Vj@`@z@Nn@Dj@Jh@?^AVA?AX?fALfAPp@PP^L^LNBCNY~BETHd@~@fCZz@dAtCeAuC[{@?A_AeCIe@Hd@~@fCZz@dAtCr@dCRtABf@RvB@@jA~NPdALj@?@x@|CXhANN\\?T??lA~@???v@@P??wAvD@lEDb@J~@x@|@t@B@j@h@dAb@@@`Bn@XJh@d@f@j@Hb@XfBLbAPj@f@hABB|@zBlBjEfDhGDFfAbBJf@Kg@gAcBACCCgDiGmBkElBjEfDhGDFfAbBJf@T`@CRB\\?Zc@nDa@pDe@zDOnANmA?Ad@{De@zDOnAG`@e@xEk@vDS~AAFCJ?DId@??U`BQnAoCu@{A]kDaAu@hEg@xC?HCDGCKEKhBc@fCGjAxAfB@B@NBZf@f@nBBf@N?G"
                },
                "mode": "BUS",
                "notes": null,
                "realTime": false,
                "rentedBike": false,
                "route": "7M",
                "routeColor": null,
                "routeId": "2066",
                "routeLongName": "AV.ALIADOS (Desc)",
                "routeShortName": "7M",
                "routeTextColor": null,
                "routeType": 3,
                "serviceDate": "20160518",
                "startTime": 1463532246000,
                "steps": [],
                "to": {
                    "arrival": 1463533035000,
                    "departure": 1463533036000,
                    "lat": 41.1512427742,
                    "lon": -8.6094696395,
                    "name": "TRINDADE",
                    "orig": null,
                    "platformCode": null,
                    "stopCode": null,
                    "stopId": {
                        "agencyId": "22",
                        "id": "22353"
                    },
                    "stopIndex": 41,
                    "zoneId": null
                },
                "transitLeg": true,
                "tripBlockId": null,
                "tripId": "117716",
                "tripShortName": null
            },
            {
                "agencyId": null,
                "agencyName": null,
                "agencyTimeZoneOffset": 3600000,
                "agencyUrl": null,
                "alerts": null,
                "alightRule": null,
                "arrivalDelay": 0,
                "boardRule": null,
                "departureDelay": 0,
                "distance": 52.471731385410536,
                "duration": 42,
                "endTime": 1463533078000,
                "from": {
                    "arrival": 1463533035000,
                    "departure": 1463533036000,
                    "lat": 41.15127546620941,
                    "lon": -8.60943102181194,
                    "name": "TRINDADE",
                    "orig": null,
                    "platformCode": null,
                    "stopCode": null,
                    "stopId": {
                        "agencyId": "22",
                        "id": "22353"
                    },
                    "stopIndex": null,
                    "zoneId": null
                },
                "headsign": null,
                "headway": null,
                "interlineWithPreviousLeg": false,
                "intermediateStops": null,
                "isNonExactFrequency": null,
                "legGeometry": {
                    "length": 8,
                    "levels": null,
                    "points": "mjdzF~ops@A?UROGQHCBGFKJ"
                },
                "mode": "WALK",
                "notes": null,
                "realTime": false,
                "rentedBike": false,
                "route": "",
                "routeColor": null,
                "routeId": null,
                "routeLongName": null,
                "routeShortName": null,
                "routeTextColor": null,
                "routeType": null,
                "serviceDate": null,
                "startTime": 1463533036000,
                "steps": [
                    {
                        "absoluteDirection": "NORTHWEST",
                        "alerts": null,
                        "area": false,
                        "bogusName": false,
                        "distance": 16.289731692813195,
                        "elevation": [],
                        "exit": null,
                        "lat": 41.15127546620941,
                        "lon": -8.60943102181194,
                        "relativeDirection": "DEPART",
                        "stayOn": false,
                        "streetName": "parking aisle"
                    },
                    {
                        "absoluteDirection": "NORTH",
                        "alerts": null,
                        "area": false,
                        "bogusName": false,
                        "distance": 36.18199969259734,
                        "elevation": [],
                        "exit": null,
                        "lat": 41.151399,
                        "lon": -8.6095356,
                        "relativeDirection": "SLIGHTLY_RIGHT",
                        "stayOn": false,
                        "streetName": "Rua da Trindade"
                    }
                ],
                "to": {
                    "arrival": 1463533078000,
                    "departure": 1463533255000,
                    "lat": 41.1516838,
                    "lon": -8.6096613,
                    "name": "TRINDADE",
                    "orig": null,
                    "platformCode": null,
                    "stopCode": null,
                    "stopId": {
                        "agencyId": "22",
                        "id": "21521"
                    },
                    "stopIndex": null,
                    "zoneId": null
                },
                "transitLeg": false,
                "tripBlockId": null,
                "tripId": null,
                "tripShortName": null
            },
            {
                "agencyId": "22",
                "agencyName": "STCP",
                "agencyTimeZoneOffset": 3600000,
                "agencyUrl": "http://www.STCP.pt",
                "alerts": null,
                "alightRule": null,
                "arrivalDelay": 0,
                "boardRule": null,
                "departureDelay": 0,
                "distance": 2030.2145436348246,
                "duration": 385,
                "endTime": 1463533640000,
                "from": {
                    "arrival": 1463533078000,
                    "departure": 1463533255000,
                    "lat": 41.1517853995,
                    "lon": -8.60952492041,
                    "name": "TRINDADE",
                    "orig": null,
                    "platformCode": null,
                    "stopCode": null,
                    "stopId": {
                        "agencyId": "22",
                        "id": "21521"
                    },
                    "stopIndex": 1,
                    "zoneId": null
                },
                "headsign": null,
                "headway": null,
                "interlineWithPreviousLeg": false,
                "intermediateStops": null,
                "isNonExactFrequency": null,
                "legGeometry": {
                    "length": 75,
                    "levels": null,
                    "points": "smdzFppps@HLq@`AG?sCI}BG?eDK?A@CB??ABAxDUGQAa@?WIc@]c@c@A?CAKO[Wa@Mm@Ac@??vCGtH??ChAgBCmDC]??T?t@???`@?a@?u@?U?T?t@?`@g@^[Ke@MeBOiD}@kASgBYcBYeAQ??k@KuEm@iEm@y@E}AE??}BG{ACwAEeFzAKFE??@u@RcB\\_@NoA`@cDdAA?YJo@TE?"
                },
                "mode": "BUS",
                "notes": null,
                "realTime": false,
                "rentedBike": false,
                "route": "4M",
                "routeColor": null,
                "routeId": "1212",
                "routeLongName": "MAIA (Asc)",
                "routeShortName": "4M",
                "routeTextColor": null,
                "routeType": 3,
                "serviceDate": "20160518",
                "startTime": 1463533255000,
                "steps": [],
                "to": {
                    "arrival": 1463533640000,
                    "departure": 1463533641000,
                    "lat": 41.1688330019,
                    "lon": -8.61232304853,
                    "name": "C. SAÃšDE PARANHOS",
                    "orig": null,
                    "platformCode": null,
                    "stopCode": null,
                    "stopId": {
                        "agencyId": "22",
                        "id": "21102"
                    },
                    "stopIndex": 8,
                    "zoneId": null
                },
                "transitLeg": true,
                "tripBlockId": null,
                "tripId": "113227",
                "tripShortName": null
            },
            {
                "agencyId": null,
                "agencyName": null,
                "agencyTimeZoneOffset": 3600000,
                "agencyUrl": null,
                "alerts": null,
                "alightRule": null,
                "arrivalDelay": 0,
                "boardRule": null,
                "departureDelay": 0,
                "distance": 298.1752361575192,
                "duration": 232,
                "endTime": 1463533873000,
                "from": {
                    "arrival": 1463533640000,
                    "departure": 1463533641000,
                    "lat": 41.16876345601781,
                    "lon": -8.612490710893281,
                    "name": "C. SAÃšDE PARANHOS",
                    "orig": null,
                    "platformCode": null,
                    "stopCode": null,
                    "stopId": {
                        "agencyId": "22",
                        "id": "21102"
                    },
                    "stopIndex": null,
                    "zoneId": null
                },
                "headsign": null,
                "headway": null,
                "interlineWithPreviousLeg": false,
                "intermediateStops": null,
                "isNonExactFrequency": null,
                "legGeometry": {
                    "length": 5,
                    "levels": null,
                    "points": "wwgzFbcqs@n@SXKqGyHgAsA"
                },
                "mode": "WALK",
                "notes": null,
                "realTime": false,
                "rentedBike": false,
                "route": "",
                "routeColor": null,
                "routeId": null,
                "routeLongName": null,
                "routeShortName": null,
                "routeTextColor": null,
                "routeType": null,
                "serviceDate": null,
                "startTime": 1463533641000,
                "steps": [
                    {
                        "absoluteDirection": "SOUTH",
                        "alerts": null,
                        "area": false,
                        "bogusName": false,
                        "distance": 43.163642312016265,
                        "elevation": [],
                        "exit": null,
                        "lat": 41.16876345601781,
                        "lon": -8.612490710893281,
                        "relativeDirection": "DEPART",
                        "stayOn": false,
                        "streetName": "Rua do Vale Formoso"
                    },
                    {
                        "absoluteDirection": "NORTHEAST",
                        "alerts": null,
                        "area": false,
                        "bogusName": false,
                        "distance": 255.0115938455029,
                        "elevation": [],
                        "exit": null,
                        "lat": 41.1683952,
                        "lon": -8.6123373,
                        "relativeDirection": "HARD_LEFT",
                        "stayOn": false,
                        "streetName": "Rua Professor Joaquim Bastos"
                    }
                ],
                "to": {
                    "arrival": 1463533873000,
                    "departure": null,
                    "lat": 41.17012963771876,
                    "lon": -8.610344089436168,
                    "name": "Rua Professor Joaquim Bastos",
                    "orig": "",
                    "platformCode": null,
                    "stopCode": null,
                    "stopId": null,
                    "stopIndex": null,
                    "zoneId": null
                },
                "transitLeg": false,
                "tripBlockId": null,
                "tripId": null,
                "tripShortName": null
            }
        ],
        "startTime": 1463528143000,
        "tooSloped": false,
        "transfers": 2,
        "transitTime": 1867,
        "waitingTime": 333,
        "walkDistance": 4593.981508093381,
        "walkLimitExceeded": false,
        "walkTime": 3530
    }
]